### ISSUE TITLE
Bug with joins statement

### ISSUE THREAD

**Issue by luongnt2** [go-gorm/hints#73]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

FROM `histories` LEFT JOIN `game_gifts` as gi on gi.`id` = `game_gift_id` LEFT JOIN `gifts` as gs on gs.`id` = gi.`gift_id` USE INDEX (`histories_created_at_status_idx`) WHERE ...

**Comment by jinzhu** [comment]
what's the problem, looks good to me?

https://dev.mysql.com/doc/refman/8.0/en/join.html

If there are any issue, please create a reproducible PR on github.com/go-gorm/gorm

Thank you.
